name: deploy-my-website 

# on: [workflow_dispatch]

# added permissions on token
permissions:
  id-token: write
  contents: read

jobs:
  say-hello:
      name: Website Deployment
      runs on: ubuntu-latest  
      steps:
        - name: Check code
          uses: actions/checkout@v2
          with:
            path: repo 
        - name: Check login and credentials
          uses: azure/login@v1
          with:
            client-id: ${{secrets.AZURE_CLIENT_ID}}
            tenant-id: ${{secrets.AZURE_TENANT_ID}}
            subscription-id: ${{secrets.SUBSCRIPTION_ID}}


         